### ISSUE TITLE
Access to Yandex.disk

### ISSUE THREAD

**Issue by myadegar** [grenlayk/text-deep-fake#10]
How can I access to Yandex.disk of your project?
it needs a token and pass.

**Comment by grenlayk** [comment]
Hi!

For now we would prefer not to share credentials because we use private cloud space. We plan to write clear specification how to download all necessary datasets till the end of June (as it is the end if semester and this work is a course work for as). 

For now we can advise you to download datasets by yourself and put it in `data` folder. Also comment all lines where we use disk instance. Sorry for inconvenience, we will sort it out soon.
For colorization branch we use [COCO dataset](https://cocodataset.org/#home)
For main problem we use [IMGUR5K dataset](https://github.com/facebookresearch/IMGUR5K-Handwriting-Dataset)

**Comment by myadegar** [comment]
Thank you
I'm waiting for that to be released.

**Comment by grenlayk** [comment]
Hi @myadegar, it's been a long time, but we finally added all necessary changes and instructions to the repo and readme, so now you can launch it if you still want :)

**Comment by myadegar** [comment]
Thanks.
